### ISSUE TITLE
react implementation for filepond-plugin-pdf-preview

### ISSUE THREAD

**Issue by bronz3beard** [Adri-Glez/filepond-plugin-pdf-preview#15]
hello, I am trying to get the preview to be shown using the react implementation and for some reason I cant see the PDF preview. I suspect it is my implementation but but I would like to make sure. (image and media previews are working 👌)

> apologies for raising an issue on something that might not be an issue, I only raise it as I have not been able to find anyone with a similar problem on SO and the AI was not helpful 😅

### Imports
```ts
    import 'filepond-plugin-image-preview/dist/filepond-plugin-image-preview.css'
    import 'filepond-plugin-media-preview/dist/filepond-plugin-media-preview.min.css'
    import 'filepond-plugin-pdf-preview/dist/filepond-plugin-pdf-preview.min.css'
    import 'filepond/dist/filepond.min.css'
```
### Registerstration
```ts
    registerPlugin(
      FilePondPluginImageExifOrientation,
      FilePondPluginFileValidateSize,
      FilePondPluginImagePreview,
      FilePondPluginMediaPreview,
      FilePondPluginPdfPreview
    )
```

### PDF preview props
```ts
    const pdfPreviewProps = {
      allowPdfPreview: withPreview,
      pdfPreviewHeight: withPreview ? 140 : 0,
      pdfComponentExtraParams:
        'toolbar=0&view=fit&page=1&navpanes=0&scrollbar=1&zoom=100'
    }
```

### FilePond component
```ts
          <FilePond
            ref={ref}
            name={name}
            labelIdle="" // we have a custom label do not add anything to this string.
            files={files}
            maxFileSize={`${maxSize}MB`}
            maxFiles={maxFiles}
            disabled={disabled}
            // allowFileSizeValidation
            // allowFileTypeValidation
            acceptedFileTypes={accept}
            allowDrop
            dropOnElement
            // dropValidation
            allowSyncAcceptAttribute={false}
            allowMultiple={allowMultiple}
            // allowRevert
            allowProcess
            allowRemove
            allowImageExifOrientation
            allowReorder={withReorder}
            allowImagePreview={withPreview}
            imagePreviewHeight={withPreview ? 140 : 0}
            imagePreviewMaxHeight={withPreview ? 140 : 0}
            imagePreviewMarkupShow={false}
            imagePreviewTransparencyIndicator="rgba(0, 0, 0, 0.0)"
            styleButtonRemoveItemPosition={
              withPreview ? 'bottom right' : 'top left'
            }
            styleButtonProcessItemPosition="right"
            styleProgressIndicatorPosition="left"
            styleLoadIndicatorPosition="bottom left"
            onupdatefiles={handleFileChange}
            oninit={() => {
              console.log('🚀 ~~ init FilePond ~~')
            }}
            server={{ process, revert }}
            {...mediaPreviewProps} // this is like this to keep typescript from complaining about missing types
            {...pdfPreviewProps} // this is like this to keep typescript from complaining about missing types
          />
  ```

Here we can see the pdf preview local blob url is there and it is working when i got to the URL directly, so maybe this issue is related to styles?

![Screenshot 2024-12-17 at 10 18 08 am](https://github.com/user-attachments/assets/d2be4262-ad32-4ced-aca4-afc76d4bb7c7)
![Screenshot 2024-12-17 at 10 19 06 am](https://github.com/user-attachments/assets/36b2a057-1b8a-4b4d-bfe1-a23d43fe4d30)

just incase these are my custom styling

```css
.filepond--wrapper {
  min-height: 15rem !important;
}

.filepond--list-scroller {
  position: relative !important;
}

.filepond--list {
  position: relative !important;
  left: 0 !important;
  right: 0 !important;
  display: flex !important;
  flex-direction: row !important;
  flex-wrap: wrap !important;
  justify-content: center !important;
  align-items: center !important;
  width: 100% !important;
}
.filepond--item {
  border-radius: 8px;
  width: 240px !important;
  background-color: transparent !important;
}

.filepond--panel .filepond--panel-root {
  border-radius: 0px;
  border-top-right-radius: 8px;
  border-top-left-radius: 8px;
  border: none;
  background-color: transparent;
}
.filepond--drop-label {
  height: 15rem !important;
  border-radius: 8px;
  cursor: pointer;
}

.filepond--credits {
  display: none !important;
}

/* .filepond--file video {
  height: 140px !important;
} */
.filepond--file-wrapper {
  border-radius: 8px !important;
  /* height: 140px !important; */
  background-color: transparent !important;
}
/* .filepond--file .filepond--media-preview-wrapper .filepond--media-preview {
  height: 140px !important;
} */

@media screen and (max-width: 768px) {
  .filepond--list {
    flex-direction: column !important;
  }

  .filepond--item {
    width: 100% !important;
    /* height: 240px !important; */
    margin: 0 auto !important;
    margin-top: 1rem !important;
    margin-bottom: 1rem !important;
  }
  .filepond--file video {
    width: 100% !important;
    /* height: 240px !important; */
  }
}

```
